---
title: "LaRs"
author: "WB"
date: "2024-05-09"
output: html_document
---
## Set-up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(haven)
library(dplyr)
library(tidyr)
library(ggplot2)
library(forcats)
library(nnet)
library(NHANES)
library(MASS)
library(naniar)
library(Hmisc)
library(mice)
library(ggeffects)
library(stringr)
library(kableExtra)
library(survey)
library(purrr)
library(RColorBrewer)
setwd("~/Documents/UCI/Analysis/LandRFinalreport/Clean-up")
rm(list = ls())
df_raw1 <- read.csv("Chunkscodes.csv")
```

## Cleaning

```{r cars}
# rename variables
df <- df_raw1
df <- df %>% 
  dplyr::rename(domain = WB.CFIR.domain,
                construct = WB.CFIR.construct)

# standardize the domain values as they are spelled differently, use capitalizations differently etc.

df$domain <- ifelse(
  str_detect(df$domain, "Imp"),
  "Process",
  df$domain
)
df$domain <- ifelse(
  str_detect(df$domain, ("Ind|Ini")),
  "Individuals",
  df$domain
)
df$domain <- ifelse(
  str_detect(df$domain, ("Inno")),
  "Innovation",
  df$domain
)
df$domain <- ifelse(
  str_detect(df$domain, ("Inner")),
  "Inner",
  df$domain
)
df$domain <- ifelse(
  str_detect(df$domain, ("Out")),
  "Outer",
  df$domain
)

## Seems that I have put a construct in the domain column for three chunks in row 657, 706 and 708:
table(df$domain)
which(df$domain=="Engaging")

## I will just manually replace them with the appropriate domains and constructs but if there were more instances of this, it would probably be worth piping the response and looping to avoid errors. 

df[717, 8] = "Process"
df[717, 9] = "Engaging: Innovation recipients"
df[719, 8] = "Process"
df[719, 9] = "Engaging: Innovation recipients"

# standardize the construct values as they are spelled differently, use capitalizations differently etc.
replacements <- list(
  "Access" = "Access to knowledge and information",
  "Adaptabilty" = "Adaptability",
  "Asessing context|Assessing Context" = "Assessing context",
  "Assessing needs: Implementation deliverers|Assessing Needs: Innovation Deliverers|Assessing Needs: Innovation deliverers|Assessing needs: innovation deliverers|^Assesing needs: Innovation deliverers$" = "Assessing needs: Innovation deliverers",
  "Assessing needs: innovation recipients|Assessing Needs: innovation recipients|Assessing Needs: Innovation Recipients|Assessing Needs: Innovation recipients| Assessing needs: Innovation recipients|Assessing context: I" = "Assessing needs: Innovation recipients",
  "Assessing Needs \\(no subconstruct\\)" = "Assessing needs (no subconstruct)",
  "Available Resources|Available resources (no further subconstruct)|Available resources (no subconstructors)" = "Available resources (no subconstruct)",
  "Crticial incidents|Critical Incidents" = "Critical incidents",
  "Culture" = "Culture (no subconstruct)",
  "Engaging: Implementation deliverers|Engaging: Innovaiton deliverers|Engaging: Innovation Deliverers" = "Engaging: Innovation deliverers",
  "Engaging: Implementation recipients|Engaging: Innovaiton recipients|Engaging: Innovation Recipients" = "Engaging: Innovation recipients",
  "^Engaging$" = "Engaging (no subconstruct)",
  "Evidence-based" = "Evidence-base",
  "Implementation deliverers" = "Innovation deliverers",
  "Innovaiton recipients|Innovation Recipients" = "Innovation recipients",
  "^Local conditions $|^Local Conditions$" = "Local conditions",
  "^Innovation Design$" = "Design",
  "^External Pressure$|External Pressures" = "External pressure",
  "^Materials and equipment$|^Materials $" = "Materials & equipment",
  "MIssion Alignment" = "Mission alignment",
  "Other (Whoever vendors are…)" = "Implementation facilitators",
  "Policies & Laws" = "Policies & laws",
  "\\bReflecting & Evaluating: Implementation\\b|\\bReflecting and evaluating: implementation\\b|\\bReflecting and Evaluating: Implementation\\b|\\bReflecting and evaluating: Implementation\\b|\\bReflecting and evluating: implementation\\b|\\bReflection and evaluation: implementation\\b|\\bReflecting and evalauting: Implementation\\b|\\bReflecting & Evaluating\\s*\\d*\\. Implementation\\b" = "Reflecting and evaluating: Implementation",
  "\\bReflecting and evaluating: Innovation\\b|\\bReflecting and Evaluating: Innovation\\b|\\bReflecting and evaluating: innovation\\b|\\bReflecting and evalauting: Innovation\\b|\\bReflecting and evluating: innovation\\b|\\bReflection and evaluation: innovation\\b|\\bReflecting and evaluating \\(innovation\\)\\b" = "Reflecting and evaluating: Innovation",
  "^Reflecting and evaluating$|^Reflecting and Evaluating$|^Reflecting and Evaluating \\(not sure which implementation or innovation - maybe both\\?\\)$" = "Reflecting and evaluating (no subconstruct)",
  "Relational Connections" = "Relational connections",
  "Relative Advantage" = "Relative advantage",
  "Structural characteristic: Work infrastructure|Structural Characteristics: Work Infrastrcuture|Structural characteristics: Work Infrastructure|Structural Characteristics: Work Infrastructure|Structural characteristics: Work infrastucture|Structural charactersitics: Work infrastructure|Structural characterstics: Work infrastructure|^Work Infrastructure$" = "Structural characteristics: Work infrastructure",
  "Structural characteristics: information Technology Infrastructure|Structural characteristics: Information Technology Infrastructure|Structural Characteristics: Information Technology Infrastructure|Structural characteristics: Informationt Technology infrastructure|Structural Characteristics: IT" = "Structural characteristics: Information technology infrastructure",
  "^Structural characteristics$|^Structural Characteristics$|^Structural characterstics$" = "Structural characteristics (no subconstruct)",
  "Taiiloring strategies|Tailoring Strategies|Tailoring" = "Tailoring strategies"
)

# Loop through the replacements and apply them
for (pattern in names(replacements)) {
  df$construct <- ifelse(
    grepl(pattern, df$construct, ignore.case = TRUE),
    replacements[[pattern]],
    df$construct
  )
}

## some constructs are weird and aren't playing nice with str_detect probably because of parentheses so will just be hard coding a replacement. 
which(df$domain=="???")
df[15, 9] = "Cost"
df[208, 9] = "Implementation facilitators"
which(df$construct=="Partnership")
df[1148, 9] = "Partnerships & connections"
which(df$construct=="Materials")
df[2395,9] = "Materials & equipment"
which(df$construct=="Process")
df[1653,9] = "Planning"
which(df$domain=="Assessing needs")
df[301,8] ="Process"
df[1214,9] ="Adapting"
df[1266, 9] = "Teaming"
# clean for year
df$year <- df$Report
df$year <- gsub("^Y1.*", "1", df$year)
df$year <- gsub("^Y2.*", "2", df$year)
df$year <- gsub("^Y3.*", "3", df$year)
df$year <- gsub("^Y4.*", "4", df$year)
df$year <- gsub("^Y5.*", "5", df$year)
## IS A STOP GAP BEFORE RECODING MISSING VALUES
values_to_drop <- c("")
df <- df[!(df$year %in% values_to_drop), ]
df <- df[!(df$domain %in% values_to_drop), ]
df <- df[!(df$construct %in% values_to_drop), ]

```

## Visualization 

You can also embed plots, for example:

```{r pressure, echo=FALSE}
## check for length of learnings and recommendations 
df$length <- str_count(df$Heading.1, "\\w+")
df$char_count <- nchar(df$Heading.1)

df$charperword <- df$char_count/df$length

df %>%
    group_by(year) %>%
    summarise(mean = mean(length)) %>%
    ggplot(aes(x = year, y = mean, color=year)) +
    geom_point(size=3) +
    geom_line() +
    labs(title = "Average words per learning/recommendation by year", x = "Year", y = "Mean Words per L&R") + theme_bw()

df %>%
    group_by(year) %>%
    summarise(mean = mean(char_count)) %>%
    ggplot(aes(x = year, y = mean, color=year)) +
    geom_point(size=3) +
    geom_line() +
    labs(title = "Average characters per learning/recommendation by year", x = "Year", y = "Mean chars per L&R") + theme_bw()

#1. Pie chart domain props combined across years
df %>%
    count(domain) %>%
    mutate(percentage = n / sum(n) * 100) %>%
    ggplot(aes(x = "", y = percentage, fill = domain)) +
    geom_bar(stat = "identity", width = 1) +
    coord_polar("y", start = 0) +
    theme_void() +
    scale_fill_brewer(palette = "Pastel1", name = "Domain") +
    labs(title = "Percentage of Each Domain across all years") +
    geom_text(aes(label = paste0(round(percentage), "%")), position = position_stack(vjust = 0.5)) +
    guides(domain = guide_legend(title = "Domain")) 


#2a. Domain count and props by year. 
df %>% 
ggplot(., aes(x = year, fill = domain)) +
    geom_bar() + theme_bw() + scale_fill_brewer(palette = "Pastel1") + labs(title="Domain counts across years")

df %>% 
ggplot(., aes(x = year, fill = domain)) +
    geom_bar(position = "fill") + theme_bw() + scale_fill_brewer(palette = "Pastel1") + labs(y="Prop", title="Domain proportions across years")

#2b. Domains props by year. 
p1 <-df %>%
    filter(year==1) %>% 
    count(domain) %>%
    mutate(percentage = n / sum(n) * 100) %>%
    ggplot(aes(x = "", y = percentage, fill = domain)) +
    geom_bar(stat = "identity", width = 1) +
    coord_polar("y", start = 0) +
    theme_void() +
    scale_fill_brewer(palette = "Pastel1", name = "Domain") +
    labs(title = "Percentage of Each Domain Year 1") +
    geom_text(aes(label = paste0(round(percentage), "%")), position = position_stack(vjust = 0.5)) +
    guides(domain = guide_legend(title = "Domain")) 
p2 <- df %>%
    filter(year==2) %>% 
    count(domain) %>%
    mutate(percentage = n / sum(n) * 100) %>%
    ggplot(aes(x = "", y = percentage, fill = domain)) +
    geom_bar(stat = "identity", width = 1) +
    coord_polar("y", start = 0) +
    theme_void() +
    scale_fill_brewer(palette = "Pastel1", name = "Domain") +
    labs(title = "Percentage of Each Domain Year 2") +
    geom_text(aes(label = paste0(round(percentage), "%")), position = position_stack(vjust = 0.5)) +
    guides(domain = guide_legend(title = "Domain")) 
p3 <- df %>%
    filter(year==3) %>% 
    count(domain) %>%
    mutate(percentage = n / sum(n) * 100) %>%
    ggplot(aes(x = "", y = percentage, fill = domain)) +
    geom_bar(stat = "identity", width = 1) +
    coord_polar("y", start = 0) +
    theme_void() +
    scale_fill_brewer(palette = "Pastel1", name = "Domain") +
    labs(title = "Percentage of Each Domain Year 3") +
    geom_text(aes(label = paste0(round(percentage), "%")), position = position_stack(vjust = 0.5)) +
    guides(domain = guide_legend(title = "Domain")) 
p4 <- df %>%
    filter(year==4) %>% 
    count(domain) %>%
    mutate(percentage = n / sum(n) * 100) %>%
    ggplot(aes(x = "", y = percentage, fill = domain)) +
    geom_bar(stat = "identity", width = 1) +
    coord_polar("y", start = 0) +
    theme_void() +
    scale_fill_brewer(palette = "Pastel1", name = "Domain") +
    labs(title = "Percentage of Each Domain Year 4") +
    geom_text(aes(label = paste0(round(percentage), "%")), position = position_stack(vjust = 0.5)) +
    guides(domain = guide_legend(title = "Domain")) 
p5 <- df %>%
    filter(year==5) %>% 
    count(domain) %>%
    mutate(percentage = n / sum(n) * 100) %>%
    ggplot(aes(x = "", y = percentage, fill = domain)) +
    geom_bar(stat = "identity", width = 1) +
    coord_polar("y", start = 0) +
    theme_void() +
    scale_fill_brewer(palette = "Pastel1", name = "Domain") +
    labs(title = "Percentage of Each Domain Year 5") +
    geom_text(aes(label = paste0(round(percentage), "%")), position = position_stack(vjust = 0.5)) +
    guides(domain = guide_legend(title = "Domain")) 

p1
p2
p3
p4
p5
combined_plots <- p1 + p2 + p3 + p4 + p5
combined_plots
#3. 
df %>%
    group_by(year, domain) %>%
    summarise(count = n()) %>%
    group_by(year) %>%
    mutate(proportion = count / sum(count)) %>%
    ggplot(aes(x = year, y = proportion, group = domain, color = domain)) +
    geom_line() +
    scale_colour_brewer(palette = "Set1", name = "Domain") +
    labs(title = "Proportion of domains by year",
         x = "Year", y = "Proportion",
         color = "Domain") +
  geom_point() +
  scale_y_break(c(0.2, 0.55), scale=1, space=0)+
  theme_bw()

#3b maybe do a change from baseline statistic as opposed to total proportion. 

#4. 
df %>%
    group_by(domain, construct) %>%
    summarise(count = n()) %>%
    mutate(percentage = (count / nrow(df)) * 100,
           domain = first(domain)) %>%
    arrange(domain, construct) %>%
    print(n = 60)

# constructs by domain
df %>%
    filter(domain == "Process") %>%
    group_by(construct, year) %>%
    summarise(count = n()) %>% 
    arrange(year, desc(count))

df %>%
  filter(domain == "Process") %>%
  ggplot(aes(x = year, fill = construct))+
  geom_bar(position="fill") + theme_bw() + labs(title="Domain: Implementation Process", y="prop")

df %>%
    filter(domain == "Individuals") %>%
    group_by(construct, year) %>%
    summarise(count = n()) %>%
    group_by(year) %>%
    mutate(percentage = count / sum(count) * 100) %>%
    arrange(year)

df %>%
  filter(domain == "Individuals") %>%
  ggplot(aes(x = year, fill = construct))+
  geom_bar(position="fill") + ylab("prop") + theme_bw() + scale_fill_brewer(palette = "Pastel1") + labs(title="Domain: Individuals", y="prop")

df_individuals <- df %>% 
    filter(domain=="Individuals")
construct_labels <- c("High-level leaders",
                        "Implementation facilitators",
                        "Innovation deliverers",
                        "Innovation recipients")
df_individuals$construct <- factor(df_individuals$construct, levels = construct_labels)
df_individuals %>%
  ggplot(aes(x = year, fill = construct))+
  geom_bar(position="fill") + ylab("prop") + theme_bw() + scale_fill_brewer(palette = "Pastel1") + labs(title="Domain: Individuals", y="prop")


df %>%
  filter(domain == "Innovation") %>%
  ggplot(aes(x = year, fill = construct))+
  geom_bar(position="fill") + ylab("prop") + theme_bw() + scale_fill_brewer(palette = "Pastel1") + labs(title="Domain: Innovation", y="prop")

df_innovation <- df %>% 
    filter(domain=="Innovation")
construct_labels <- c("Adaptability",
                        "Complexity",
                        "Cost",
                        "Design",
                        "Evidence-base",
                        "Innovation recipients",
                        "Relative advantage",
                        "Source")
df_innovation$construct <- factor(df_innovation$construct, levels = construct_labels)

df %>%
  filter(domain == "Inner") %>%
  ggplot(aes(x = year, fill = construct))+
  geom_bar(position="fill") + ylab("prop") + theme_bw() + labs(title="Domain: Inner setting", y="prop")

df_inner <- df %>% 
    filter(domain=="Inner")
construct_labels <- c("Access to knowledge and information",
                      "Available resources (no subconstruct)",
                      "Communications",
                      "Compatibility",
                      "Culture (no subconstruct)",
                      "Innovation recipients",
                      "Local conditions",
                      "Materials & equipment",
                      "Mission alignment",
                      "Relational connections",
                      "Relative priority",
                      "Structural characteristics (no subconstruct)",
                      "Structural characteristics: Information technology infrastructure",
                      "Structural characteristics: Physical infrastructure",
                      "Structural characteristics: Work infrastructure")
df_inner$construct <- factor(df_inner$construct, levels = construct_labels)
df_inner %>%
            filter(year == 1) %>% 
            count(construct) %>%
            complete(construct = construct_labels, fill = list(n = 0)) %>%
            mutate(percentage = n / sum(n) * 100) %>%
            arrange(construct)

df_outer <- df %>% 
    filter(domain=="Outer")
construct_labels <- c("High-level leaders",
                           "External pressure",
                           "Local attitudes",
                           "Local conditions",
                           "Partnerships & connections",
                           "Policies & laws")

df_outer %>% 
    group_by(construct, year) %>%
    summarise(count = n()) %>%
    group_by(year) %>%
    mutate(percentage = count / sum(count) * 100) %>%
    arrange(year)

df_outer$construct <- factor(df_outer$construct, levels = construct_labels)
df_outer %>%
            filter(year == 1) %>% 
            count(construct) %>%
            complete(construct = construct_labels, fill = list(n = 0)) %>%
            mutate(percentage = n / sum(n) * 100) %>%
            arrange(construct)

df %>%
  filter(domain == "Outer") %>%
  ggplot(aes(x = year, fill = construct))+
  geom_bar(position="fill") + ylab("prop") + theme_bw() + scale_fill_brewer(palette = "Pastel1") + labs(title="Domain: Outer setting", y="prop")

df_process <- df %>% 
    filter(domain=="Process")
construct_labels <- c("Adaptability",
                        "Adapting",
                        "Assessing context",
                        "Assessing needs",
                        "Assessing needs: Innovation deliverers",
                        "Communications",
                        "Doing",
                        "Engaging",
                        "Engaging: Innovation deliverers",
                        "Innovation recipients",
                        "Planning",
                        "Process",
                        "Reflecting and evaluating",
                        "Reflecting and evaluating: Implementation",
                        "Reflecting and evaluating: Innovation",
                        "Tailoring strategies",
                        "Teaming")
df_process$construct <- factor(df_process$construct, levels = construct_labels)

df_outer %>%
            filter(year == 1) %>% 
            count(construct) %>%
            complete(construct = construct_labels, fill = list(n = 0)) %>%
            mutate(percentage = n / sum(n) * 100) %>%
            arrange(construct)

## total constructs props
q <- df %>%
    group_by(domain, construct) %>%
    summarise(count = n()) %>%
    mutate(percentage = (count / nrow(df)) * 100,
           domain = first(domain)) %>%
    arrange(domain, construct) %>%
    print(n = 60)
write.csv(q, file = "constructprop.csv", row.names = TRUE)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
